### ISSUE TITLE
`href` Attribute is missing when having a `link` with multiple marks

### ISSUE THREAD

**Issue by o1y** [jacksleight/statamic-bard-mutator#13]
## Bug Description
Not sure if this is a Bard Mutator bug, but I came across an issue since Bard Mutator 2 when having a `link`, which contains multiple marks. Bard Mutator then returns just for the first link mark the `href` attribute. In the second mark `href` is not available, which may cause an error if no proper check is implemented.

## How to Reproduce
```yaml
-
  type: paragraph
  content:
    -
      type: text
      text: 'Lorem Ipsum '
    -
      type: text
      text: 'italic link'
      marks:
        -
          type: link
          attrs:
            href: /test
        -
          type: italic
    -
      type: text
      text: ' regular'
      marks:
        -
          type: link
          attrs:
            href: /test
```
```php
Mutator::html('link', function ($value) {
    $href = $value[1]['href']; // `Undefined array key "href"`
    // ... 
});
```

## Environment
```
Environment
Application Name: Statamic
Laravel Version: 9.30.1
PHP Version: 8.2.3
Composer Version: 2.5.4
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: redis
Session: file

Statamic
Addons: 1
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.5 PRO

Statamic Addons
jacksleight/statamic-bard-mutator: 2.0.1
```
