### ISSUE TITLE
Missing `info` object causing fatal error when mutating links

### ISSUE THREAD

**Issue by daun** [jacksleight/statamic-bard-mutator#34]
## Bug Description

After upgrading to `3.0`, I'm getting the following error when mutating links.

```
JackSleight\StatamicBardMutator\Plugins\ClosurePlugin::render()
Argument #2 ($info) must be of type object, null given, called in
vendor/jacksleight/statamic-bard-mutator/src/Mutator.php
on line 168
```

## How to Reproduce

I'm using the example from the docs for marking external links.

```php
Mutator::html('link', function ($value) {
  if (URL::isExternal($value[1]['href'])) {
    $value[1]['class'] = 'external';
  }
  return $value;
});
```

This is the Bard field data in question that throws. Removing it also gets rid of the exception.

```yaml
  -
    type: paragraph
    attrs:
      textAlign: left
      bts_key: null
    content:
      -
        type: text
        marks:
          -
            type: link
            attrs:
              href: 'statamic://entry::2c469569-6697-460a-ba15-b4e1d3842c3f'
              rel: null
              target: null
              title: null
        text: 'Read more'
```

That's the url that throws:

```
/manage/collections/pages/entries?sort=updated_at&order=desc&page=1&perPage=10
```

## Extra Detail

It looks like for some reason the `$info` var fetched from `Mutator::fetchInfo()` is empty for that particular node. That's where I'm getting lost on the inner workings of the addon, though :)

## Environment

```
Environment
Application Name: *****
Laravel Version: 11.26.0
PHP Version: 8.3.4
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: *****.test
Maintenance Mode: OFF
Timezone: Europe/Vienna
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: database
Session: file

Statamic
Addons: 5
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.30.0 PRO

Statamic Addons
daun/statamic-widget-collection-count: 1.2.1
doefom/currency-fieldtype: 1.4.1
jacksleight/statamic-bard-mutator: 3.0.0
jacksleight/statamic-bard-texstyle: 3.3.0
stillat/relationships: 2.2.1
```
